CREATE TABLE IF NOT EXISTS auth_users(id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL, branch_code varchar(255), created_time TIMESTAMP, first_name varchar(255) NOT NULL, hospital_code varchar(255), is_enable boolean, is_password_updated boolean, last_name varchar(255) NOT NULL, mail_id varchar(255) NOT NULL, middle_name varchar(255), password varchar(255) NOT NULL, updated_time TIMESTAMP, user_type INT, UNIQUE(mail_id));

CREATE TABLE IF NOT EXISTS user_confirmation_tokens (token_id BIGINT PRIMARY KEY NOT NULL, confirmation_token varchar(255), created_date TIMESTAMP, user_id BIGINT NOT NULL REFERENCES users(id));

CREATE TABLE IF NOT EXISTS password_reset_token_table(
token_id BIGINT PRIMARY KEY NOT NULL,
created_date TIMESTAMP,
expiry_date TIMESTAMP,
reset_token varchar(255),
user_id BIGINT NOT NULL REFERENCES users(id));

CREATE TABLE IF NOT EXISTS system_parameter(
param_id BIGINT NOT NULL PRIMARY KEY,
created_date TIMESTAMP,
description varchar(255),
is_enable BOOLEAN,
value varchar(255),
variable varchar(255)
);
